music_app/auth.py
from flask import render_template, redirect, url_for, flash, Blueprint, session
from flask_login import login_user, logout_user, current_user
from music_app.forms import LoginForm, RegistrationForm
from music_app import db
from music_app.models import User


bp = Blueprint('auth', __name__, )


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('routes.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        """ The following conditional is probably unnecessary since
        LoginForm validators for username & password were added. """
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('auth.login'))

        if form.shared.data:
            session['shared'] = True
        else:
            session['shared'] = False
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('routes.index'))

    return render_template('login.html', title='Sign In', form=form)


@bp.route('/logout')
def logout():
    if session.get('shared'):
        session.clear()
        logout_user()
        return redirect(url_for('routes.logout_spotify'))
    else:
        session.clear()
        logout_user()
        return redirect(url_for('routes.index'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('routes.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Success! You are now a registered user.')
        return redirect(url_for('auth.login'))

    return render_template('register.html', title='Register', form=form)

music_app/routes.py
from flask import render_template, request, url_for, redirect, Blueprint, \
    session, json, flash, current_app, send_from_directory
from .spotify import SpotifyHelper, ParsePlaylists
from music_app.forms import UploadForm
import os.path
from flask_login import login_required, current_user
from music_app import db
from datetime import datetime
from secrets import token_urlsafe
from more_itertools import chunked
from tempfile import NamedTemporaryFile
import csv
import re
import chardet

bp = Blueprint('routes', __name__, static_folder='./static')

sh = SpotifyHelper()
p = ParsePlaylists()
redirect_url = sh.REDIR_URL
session_expired = '''
    Your session has expired. Click "Start Your Session" to start a new one.'''
default_state = os.getenv('SPOTIFY_DEFAULT_STATE')


def get_endpoint(key):
    with open(os.path.join(bp.static_folder, 'JSON/endpoints.json')) as f:
        d = json.load(f)
    return d[key]["url"]


def list_extractor(list, key):
    """Extract a list of values from a single key in list of dictionaries."""
    values = [item[key] for item in list]
    return values


@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html')


@bp.route('/action', methods=['GET', 'POST'])
@login_required
def action():
    if current_user.is_authenticated:
        if current_user.state == default_state:
            current_user.state = token_urlsafe(12)
            db.session.commit()
        ts = current_user.token_json
        tct = current_user.token_creation_time
        status = sh.token_status(token_string=ts, token_creation_time=tct)

        if (session.get('shared')
                or status == 'expired'
                or status == 'no_token'):
            return redirect(url_for('routes.new_request'))
        else:
            return redirect(url_for('routes.profile'))
    else:
        return redirect(url_for('routes.index'))


@bp.route('/new_request', methods=['GET', 'POST'])
@login_required
def new_request():
    params = sh.AUTH_DICT
    params['state'] = current_user.state
    url = sh.auth_request(**params)
    return redirect(url)


@bp.route('/callback', methods=['GET', 'POST'])
@login_required
def callback():
    # Check that 'state' strings match.
    if current_user.state != request.args.get('state'):
        raise Exception('Cross-site request forgery')

    # Store the code so ProfileData.token_header() can access it.
    if request.args.get('code'):
        session['auth_code'] = request.args.get('code')
        return redirect(url_for('routes.profile'))
    else:
        flash('Something went wrong.')
        return redirect(url_for('routes.index'))


def token_header():
    ts = current_user.token_json
    tct = current_user.token_creation_time
    code = session.get('auth_code')
    if code:
        session['auth_code'] = ""  # Clear this after code variable is set.
    try:
        tj = sh.token_json(
            token_string=ts, token_creation_time=tct, code=code)
        if str(tj) != ts:
            current_user.token_json = str(tj)
            current_user.token_creation_time = datetime.utcnow()
            db.session.commit()
        token = tj['access_token']
        token_type = tj['token_type']
        header = {'Authorization': token_type + ' ' + token}
        return header
    except KeyError:
        current_app.logger.exception('Token expired')
        return None


class ProfileData:
    """Collect data to populate the 'profile' view."""
    def __init__(self):
        self.header = token_header()

    def mock_token_header(self):  # Pytest (../tests/conftest.py) needs this.
        pass

    def profile_(self):
        return sh.get_data(
            self.header,
            get_endpoint("get-current-user-profile")
            )

    def playlists_(self, limit=20, offset=0):
        url = (get_endpoint("get-list-of-current-user-playlists")
               + "?limit="
               + str(limit)
               + "&offset="
               + str(offset))
        return sh.get_data(self.header, url)

    def all_playlists_(self):

        # Make the first request as standard
        url = get_endpoint("get-list-of-current-user-playlists")

        playlists = []

        while True:
            result = sh.get_data(self.header, url)
            print (url)

            if 'items' not in result:
                break # Deal with an empty result set
            else:
                for item in result['items']:
                    playlists.append(item)

            if result['next'] is None:
                break
            else:
                url = result['next']

        return playlists

    def history_(self):
        return sh.get_data(
            self.header,
            get_endpoint("get-current-user-recently-played-tracks")
            )

    def top_artists_(self):
        # Build endpoint url for top artists.
        top_a_url = get_endpoint(
            "get-user-top-artists+tracks").format(type="artists")
        top_a_url = top_a_url + "?limit=50&time_range=long_term"

        return sh.get_data(self.header, top_a_url)

    def top_tracks_(self):
        # Build endpoint url for top tracks.
        top_t_url = get_endpoint(
            "get-user-top-artists+tracks").format(type="tracks")
        top_t_url = top_t_url + "?limit=50&time_range=long_term"

        return sh.get_data(self.header, top_t_url)


@bp.before_request
def header_check():
    if request.path is ('/profile'
                        or '/upload'
                        or '/retry'
                        or '/download'
                        or '/playlists'):
        header = token_header()
        if not header and not current_app.testing:
            flash(session_expired)
            return redirect(url_for('routes.index'))


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """Snapshot page of current user's profile.

    Displays playlists, recently played tracks,
    top artists, and tops tracks.
    """
    pd = ProfileData()
    missing = session.get('missing')
    retry_missing = session.get('retry_missing')
    with open(os.path.join(bp.static_folder, 'JSON/mock.json')) as f:
        mock = json.load(f)
    err_msg = 'We could not retrieve '

    try:
        profile = pd.profile_()
    except Exception as e:
        current_app.logger.exception(f'{e}: Could not retrieve user profile.')
        profile = mock['profile']
        flash(err_msg + 'user profile.')
    session["user"] = profile

    try:
        playlists = pd.playlists_()
    except Exception as e:
        current_app.logger.exception(f'{e}: Could not retrieve playlists.')
        playlists = mock['playlists']
        flash(err_msg + 'playlists.')
    session['playlists'] = []
    playlist_names = [item['name'] for item in playlists['items']]
    session['playlists'] = playlist_names

    try:
        history = pd.history_()
    except Exception as e:
        current_app.logger.exception(
            f'{e}: Could not retrieve recently played songs.')
        history = mock['history']
        flash(err_msg + 'recently played songs.')

    try:
        top_artists = pd.top_artists_()
    except Exception as e:
        current_app.logger.exception(f'{e}: Could not retrieve top artists.')
        top_artists = mock['top_artists']
        flash(err_msg + 'your top artists.')

    try:
        top_tracks = pd.top_tracks_()
    except Exception as e:
        current_app.logger.exception(f'{e}: Could not retrieve top tracks.')
        top_tracks = mock['top_tracks']
        flash(err_msg + 'your top tracks.')

    return render_template(
        'profile.html',
        playlists=playlists['items'],
        history=history['items'],
        top_artists=top_artists['items'],
        top_tracks=top_tracks['items'],
        list_extractor=list_extractor,
        missing=missing,
        retry_missing=retry_missing,
        title='Playlist-ify | Your Spotify Music'
        )


@bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    header = token_header()

    # Clear 'missing' and 'retry_missing' from session.
    session['missing'] = []
    session['retry_missing'] = []

    # Upload the playlist file.
    form = UploadForm()
    err_tracks = []
    message = ""
    if form.validate_on_submit():
        # Use the file name as the playlist name.
        file = form.upload.data
        filename = file.filename
        playlist_name = filename.split('.')[0]

        # Parse an xml playlist file.
        if filename.split('.')[-1] == 'xml':
            songs = p.parse_songs_xml(file)

        # Parse a csv or txt (actually tab-delimited csv) file.
        else:
            # Start with bytes, then encode.
            byte_str = file.read()
            try:
                u_string = byte_str.decode()
            except Exception as e:
                encoding = chardet.detect(byte_str)['encoding'].lower()
                u_string = byte_str.decode(encoding=encoding)
                current_app.logger.exception(e)
            songs = p.parse_songs_csv(u_string)

        # Create new playlist if it does not already exist.
        if playlist_name not in session['playlists']:
            params = {"name": playlist_name, "public": False}

            # Get and format endpoint URL from static/JSON/endpoints.json.
            url_create = get_endpoint(
                "create-playlist").format(user_id=session["user"]["id"])

            # Create the playlist, check if `songs` available in Spotify.
            new_playlist = sh.post_data(header, url_create, **params)
            if new_playlist[0] in [200, 201]:
                playlist_id = new_playlist[1]['id']
                tracks = sh.collect_tracks(
                    header, session['user']['country'], *songs)

    # Log and flash errors due to tracks with bad data.  See err_string below.

                for error in tracks['errors']:

music_app/templates/index.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block content %}

<div class="pad-sides header">
  <h1>Playlist<em>-ify</em></h1>
  {% if current_user.is_authenticated %}
    <div class="flex-header">
      <h4 class="flex-title">Hi {{ current_user.username }}!</h4>
      <h5>
        <a href="{{ url_for('auth.logout') }}">Logout</a>
      </h5>
    </div>
    <button><a href="{{ url_for('routes.action') }}">Start Your Session</a></button>
  {% else %}
    <p>To start your session please&nbsp;
      <a class="show-like-hover" href="{{ url_for('auth.login') }}">Login</a> or
      <a class="show-like-hover" href="{{ url_for('auth.register') }}">Register</a>
    </p>
    <button class="disabled">Start Your Session</button>
  {% endif %}
</div>
<div class="messages pad-sides">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <p class="flashed-errors">{{ message }} Did you sign into Spotify?</p>
    {% endfor %}
  {% endif %}
  {% endwith %}
</div>

<div class="pad-sides content">
  <h3>What can you do here?</h3>
  <p><strong class="app-name highlight">Exchange playlists between Apple iTunes/Music and Spotify. It's fast, free, and unlimited.</strong></p>
  <p><strong class="app-name">Import</strong> Apple playlists to Spotify or <strong class="app-name">export</strong> your Spotify playlists to files than can be easily imported to Apple Music. Share playlists with friends even if they use the other streaming service.</p>
  <p>Once you start a session and log into Spotify, you will also see a snapshot of your Spotfy account and recent activity:
    <ul>
      <li>Playlists</li>
      <li>Recently played tracks</li>
      <li>Top artists</li>
      <li>Top tracks</li>
    </ul>
  </p>
  
  <p>Clicking the "Start Your Session" button will initiate the following events:
    <ol>
      <li>If you are not already signed into Spotify, a tab will open with a Spotify login page.</li>
      <li>Once logged in, you will be asked to give <span class="app-name">Playlist-ify</span> permission to perform certain tasks.</li>
      <li>Please agree to these permissions since they are needed to retrieve your Spotify profile and allow uploading of playlists.<br>(Once these first 3 steps are done they will not need to be repeated unless you logout of Spotify or revoke <span class="app-name">Playlist-ify's</span> access.)</li>
      <li>You will be redirected to a profile page showing your Spotify snapshot. Once there, you can import an Apple playlist or download a Spotify playlist.</li>
    </ol>
  </p>
  <p>A note about PRIVACY:
    <ul>
      <li><span class="app-name">Playlist-ify</span> neither asks for nor retains any of your data or private information.</li>
      <li>Registration/login are required solely to keep track of authorization credentials.
        <br>(Allowing you to access your Spotify data through the app.)</li>
      <li>We collect no data other than username and password (encrypted & unreadable by us).
      <br>(If you forget your password, we cannot reset it. Simply re-register.)
      <li>Session data dissappears when you close your browser.
      <br>(If you login with "Stay logged in" checked, it will remember you but nothing about what you were doing in your previous seession.)</li>
    </ul>
  </p>
</div>

{% endblock %}

music_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="header pad-sides">
  <h1>Please Sign In</h1>
  <p>New User?&emsp;&emsp;
    <span class="blue-link">
      <a href="{{ url_for('auth.register') }}">Click here to Register!</a>
    </span>
  </p>
  <div class="blue-link"><a href="{{ url_for('routes.index') }}">&larr; Back to Home Page</a></div>
</div>
<div class="messages pad-sides">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      {% if "Success" in message %}
        <p class="flashed-success">{{ message }}</p>
      {% else %}
        <p class="flashed-errors">{{ message }}</p>
      {% endif %}
    {% endfor %}
  {% endif %}
  {% endwith %}
</div>
<div class="pad-sides form">
    <form method="POST">
    {{ form.hidden_tag() }}
    {% if session['shared'] %}
      <p>
        {{ form.shared(checked="checked", onchange="disableEnable()", autocomplete="off") }}
         Check here if this is a {{ form.shared.label }}
      </p>
      <p class="blue-link" id="clear_spotify">
        <a href="{{ url_for('routes.logout_spotify') }}" target="_blank">
          Clear active Spotify logins(recommended)
        </a>
      </p>
      <p>
        {{ form.remember_me.label(class_="grayed", id="remember_label") }}
         {{ form.remember_me(disabled="true", id="remember") }}
      </p>
    {% else %}
      <p>
        {{ form.shared(onchange="disableEnable()", autocomplete="off") }}
         Check here if this is a {{ form.shared.label }}
      </p>
      <p class="hidden" id="clear_spotify">
        <a href="{{ url_for('routes.logout_spotify') }}" target="_blank">
          Clear Spotify login(recommended)
        </a>
      </p>
      <p>{{ form.remember_me.label(id="remember_label") }} {{ form.remember_me(id="remember") }}</p>
    {% endif %}
    <p>{{ form.username.label }} {{ form.username }}</p>
    <div class="errors">
    {% for error in form.username.errors %}
      {{ error }}
    {% endfor %}
    </div>
    <p>{{ form.password.label }} {{ form.password }}</p>
    <div class="errors">
    {% for error in form.password.errors %}
      {{ error }}
    {% endfor %}
    </div>
    <p>{{ form.submit }}</p>
  </form>
</div>
{% endblock %}

{% block script %}
<script>
  function disableEnable() {
    var remember = document.getElementById("remember");
    var label = document.getElementById("remember_label");
    var spot = document.getElementById("clear_spotify");
    if ( remember.disabled ) {
      remember.disabled = false;
      label.className = label.className.replace("grayed", "");
      spot.className = spot.className.replace("blue-link", "hidden");
    }
    else {
      remember.disabled = true;
      label.className += " grayed";
      spot.className = spot.className.replace("hidden", "blue-link");
    }
  }
</script>
{% endblock %}

music_app/templates/playlists.html
{% extends "base.html" %}

{% block head %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="playlists pad-sides" id="playlists">
  <h3>Playlists
    <button>
      <a href="{{ url_for('routes.upload') }}">Import a Playlist</a>
    </button>
  </h3>
  <div>
    <a href="/profile">&larr; Back to Snapshot Page</a> 
  </div>
  <br>
  <small class="clickable blue-link" id="show_hide" onclick="showHideDownloads()">
    Enable playlist downloads +
  </small>
  <h5 class="hidden" id="dl_instruction">
    Click <span class="dl-icon">&darr;</span> to download as a CSV file
    <i class="material-icons csv-info clickable" onclick="showModal('info1')">info_outline</i>
    <div class="modal hidden" id="info1" onclick="closeModal(this)">
      <ul>
        <li>View as a spreadsheet</li>
        <li>Share with other Spotify users (who can import it with Playlist-ify)</li>
        <li>Share with iTunes/Music users (who can import it if the songs are in their library)</li>
      </ul>
    </div>
  </h5>
  {% for playlist in playlists %}
  {% with name = playlist.name, id = playlist.id, length = playlist.tracks.total %}
  <p>
    <a href="{{ playlist.external_urls.spotify }}" target="_blank">{{ name }}</a>
    <a class="dl-icon hidden"
      href="{{ url_for('routes.download', id=id, name=name, length=length) }}" target="_blank">
      &darr;
    </a>
  </p>
  {% endwith %}
  {% endfor %}
</div>
{% endblock %}

{% block script %}
<script>

  function showHideDownloads() {
    var playlists = document.getElementById("playlists");
    var instruction = document.getElementById("dl_instruction");
    var toggle = document.getElementById("show_hide");
    
    if ( instruction.className.indexOf("hidden") == -1 ) {
      var downloads = playlists.getElementsByClassName("dl-icon float-right");
      instruction.className += "hidden";
      toggle.innerHTML = "Enable playlist downloads +";
      while (downloads.length > 0) {
        downloads[0].classList.add("hidden");
        downloads[0].classList.remove("float-right");
      }
    }
    else {
      var downloads = playlists.getElementsByClassName("dl-icon hidden");
      instruction.className = instruction.className.replace("hidden", "");
      toggle.innerHTML = "Disable playlist downloads &mdash;";
      while (downloads.length >= 0) {
        downloads[0].classList.add("float-right");
        downloads[0].classList.remove("hidden");
      }
    }
  }

  function showModal(id) {
    var modal = document.getElementById(id);
    if (modal.className.indexOf("hidden") != -1) {
      modal.className = modal.className.replace("hidden", "");
    }
    else {
      closeModal(modal);
    }
  }

  function closeModal(element) {
    element.className += " hidden";
  }

</script>
{% endblock %}

music_app/templates/profile.html
{% extends "base.html" %}
 
{% block head %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="header sticky-header" id="header">
  <div class="pad-sides flex-container">
    <h2>Snapshot of {{ session.user.display_name }}'s Spotify Music</h2>
    <h5>
      <a href="{{ session.user.external_urls.spotify }}" target="_blank">
          Your Spotify Web Player
      </a>
    <br>
    {% if not session['shared'] %}
      <a href="{{ url_for('auth.logout') }}">Logout from Playlist-ify</a>
    <br>
      <a href="{{ url_for('routes.logout_spotify') }}" target="_blank">Logout from Spotify</a>
    <br>
      <a href="{{ url_for('routes.download', backup=True) }}" onclick="showModal('backup')">Backup My Liked Songs</a>
      <div class="modal hidden clickable" id="backup" onclick="closeModal(this)">
        <i class="material-icons">close</i> Processing your download...
      </div>
    {% else %}
      <a href="{{ url_for('auth.logout') }}">Logout from Playlist-ify & Spotify</a>
    {% endif %}
    </h5>
  </div>
  <br>
  <div>
    <nav>
      <div class="flex-container">
        <a class="nav-link" href="#playlists" onclick=moveHeader()>Playlists</a>
        <a class="nav-link" href="#recent" onclick=moveHeader()>Recently Played</a>
        <a class="nav-link" href="#top-artists" onclick=moveHeader()>Top Artists</a>
        <a class="nav-link" href="#top-tracks" onclick=moveHeader()>Top Tracks</a>
      </div>
    </nav>
  </div>
</div>
<div class="messages pad-sides">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      {% if "Success" in message %}
        <p class="flashed-success">{{ message }}</p>
      {% else %}
        <p class="flashed-errors">{{ message }}</p>
      {% endif %}
    {% endfor %}
  {% endif %}
  {% endwith %}
</div>
<div class="missing-tracks pad-sides">
{% if missing and missing|length > 0 %}
  <h4>Here is what we couldn't find...</h4>
  {% for playlist in missing %}
    <p>{{ playlist.playlist_name }}:</p>
    {% for track in playlist.tracks %}
      <p class="missing-song">{{ track }}</p>
    {% endfor %}
  {% endfor %}
  <div class="retry">
      <h4>Try searching with just the song and artist?</h4>
      <button><a href="{{ url_for('routes.retry') }}">Try it</a></button>
  </div>
{% endif %}
{% if retry_missing and retry_missing|length > 0 %}
  <h4>Here is what we couldn't find...</h4>
  {% for playlist in retry_missing %}
    <p>{{ playlist.playlist_name }}:</p>
    {% for track in playlist.tracks %}
      <p class="missing-song">{{ track }}</p>
    {% endfor %}
  {% endfor %}
  <p>Check spelling. You can also add these manually. Click the playlist below to go to Spotify.</p>
{% endif %}
</div>
<div class="playlists pad-sides" id="playlists">
  <h3>Playlists
    <button>
      <a href="{{ url_for('routes.upload') }}">Import a Playlist</a>
    </button>
  </h3>
  <small class="clickable blue-link" id="show_hide" onclick="showHideDownloads()">
    Enable playlist downloads +
  </small>
  <h5 class="hidden" id="dl_instruction">
    Click <span class="dl-icon">&darr;</span> to download as a CSV file
    <i class="material-icons csv-info clickable" onclick="showModal('info1')">info_outline</i>
    <div class="modal hidden" id="info1" onclick="closeModal(this)">
      <ul>
        <li>View as a spreadsheet</li>
        <li>Share with other Spotify users (who can import it with Playlist-ify)</li>
        <li>Share with iTunes/Music users (who can import it if the songs are in their library)</li>
      </ul>
    </div>
  </h5>
  {% for playlist in playlists %}
  {% with name = playlist.name, id = playlist.id, length = playlist.tracks.total %}
  <p>
    <a href="{{ playlist.external_urls.spotify }}" target="_blank">{{ name }}</a>
    <a class="dl-icon hidden"
      href="{{ url_for('routes.download', id=id, name=name, length=length) }}">
      &darr;
    </a>
  </p>
  {% endwith %}
  {% endfor %}
  <p>
    <small class="blue-link">
      <a href="{{ url_for('routes.playlists') }}">
        See all my playlists &rarr;
      </a>
    </small>
  </p>
</div>
<div class="recent-plays pad-sides" id="recent">
  <h3>Recently played songs</h3>
  {% for item in history %}
  {% with artists = item['track']['album']['artists'] %} 
  {% with names = list_extractor(artists, 'name') %}
    <p>
    {{ item.track.name }} | {{ item.track.album.name }} | {{ names | join(', ') }}
    </p>
  {% endwith %}
  {% endwith %}
  {% endfor %}
</div>
<div class="top-artists pad-sides" id="top-artists">
  <h3>Top Artists</h3>
  {% for artist in top_artists %}
    <p><a href="{{ artist.external_urls.spotify }}" target="_blank">{{ artist.name }}</a></p>
  {% endfor %}
</div>
<div class="top-tracks pad-sides" id="top-tracks">
  <h3>Top Tracks</h3>
  {% for track in top_tracks %}
    <p><a href="{{ track.external_urls.spotify }}" target="_blank">{{ track.name }}</a></p>
  {% endfor %}
</div>
{% endblock %}

{% block script %}
<script>
  function moveHeader() {
    var header = document.getElementById("header");
    if (header.className.indexOf("sticky-header") != -1) {
      header.className = header.className.replace("sticky-header", "");
      setTimeout(function() {
        document.addEventListener("scroll", stickHeader);
      }, 4000);
    }
  }

  function stickHeader() {
    var header = document.getElementById("header");
    if (header.className.indexOf("sticky-header") == -1) {
      header.className += "sticky-header";
      document.removeEventListener("scroll", stickHeader);
    }
  }

  function showHideDownloads() {
    var playlists = document.getElementById("playlists");
    var instruction = document.getElementById("dl_instruction");
    var toggle = document.getElementById("show_hide");
    
    if ( instruction.className.indexOf("hidden") == -1 ) {
      var downloads = playlists.getElementsByClassName("dl-icon float-right");
      instruction.className += "hidden";
      toggle.innerHTML = "Enable playlist downloads +";
      while (downloads.length > 0) {
        downloads[0].classList.add("hidden");
        downloads[0].classList.remove("float-right");
      }
    }
    else {
      var downloads = playlists.getElementsByClassName("dl-icon hidden");
      instruction.className = instruction.className.replace("hidden", "");
      toggle.innerHTML = "Disable playlist downloads &mdash;";
      while (downloads.length >= 0) {
        downloads[0].classList.add("float-right");
        downloads[0].classList.remove("hidden");
      }
    }
  }

  function showModal(id) {
    var modal = document.getElementById(id);
    if (modal.className.indexOf("hidden") != -1) {
      modal.className = modal.className.replace("hidden", "");
    }
    else {
      closeModal(modal);
    }
  }

  function closeModal(element) {
    element.className += " hidden";
  }

</script>
{% endblock %}

music_app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="header pad-sides">
  <h1>Please Register</h1>
  <div class="blue-link"><a href="{{ url_for('routes.index') }}">&larr; Back to Home Page</a></div>
</div>
<div class="messages pad-sides">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <p class="flashed-errors">{{ message }}</p>
    {% endfor %}
  {% endif %}
  {% endwith %}
</div>
<div class="pad-sides form">
  <form method="POST">
    {{ form.hidden_tag() }}
    <p>
      {{ form.username.label }} {{ form.username }}
      <div class="errors">
      {% for error in form.username.errors %}
        {{ error }}
      {% endfor %}
      </div>
    </p>
    <p>
      {{ form.password.label }} {{ form.password }}
      <div class="errors">
      {% for error in form.password.errors %}
        {{ form.password.label }}{{ error[5:] }}
      {% endfor %}
      </div>
    </p>
    <p>
      {{ form.password2.label }} {{ form.password2 }}
      <div class="errors">
      {% for error in form.password2.errors %}
        {{ form.password2.label }}{{ error[5:] }}
      {% endfor %}
      </div>
    </p>
    <p>{{ form.submit }}</p>
  </form>
</div>
{% endblock %}